Files to enable updating Twinbase instances

diff --git a/.github/workflows/file-modifier.yml b/.github/workflows/file-modifier.yml
--- a/.github/workflows/file-modifier.yml
+++ b/.github/workflows/file-modifier.yml
@@ -32,6 +32,12 @@ jobs:
       run: |
         python3 -m pip install --upgrade pip
         pip install -r requirements.txt
+    - name: Update setup
+      run: |
+        python3 ${GITHUB_WORKSPACE}/.github/setup-update.py
+        # Git operations
+        git add -A
+        git commit -m "Automodified update setup files" -a || echo "Warning: git commit returned error code $? (Hopefully nothing to commit)"
     - name: Modify twindocs
       run: |
         # Create modification lists
